CREATE TABLE pins_tags (
    id INT PRIMARY KEY AUTO_INCREMENT,
    pin_id INT,
    tag_id INT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
