CREATE TABLE boards_pins (
    id INT PRIMARY KEY AUTO_INCREMENT,
    board_id INT NOT NULL,
    pin_id INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
